SMS/Models/Domain/Enrollment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SMS.Models
{
    public class Enrollment
    {
        public int EnrollmentId { get; set; }
        public string Term { get; set; }
        public Student Student { get; set; }
        public int StudentId { get; set; }
        public ICollection<EnrollInfo> EnrollInfos { get; set; }
    }
}

SMS/Models/Enrollment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SMS.Models
{
    public class Enrollment
    {
        public int EnrollmentId { get; set; }
        public string Term { get; set; }
        public Student Student { get; set; }
        public int StudentId { get; set; }
    }
}

SMS/Controllers/EnrollmentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SMS.Controllers
{
    public class EnrollmentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SMS/Views/Enrollment/Index.cshtml
@model List<Enrollment>
@{
    ViewBag.Title = "Enrollments";
}

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Student Name</th>
            <th>Term</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var e in Model)
        {
            <tr>
                <td>@e.EnrollmentId</td>
                <td>@e.Student.Name</td>
                <td>@e.Term</td>

                <td>
                    <a asp-controller="Enrollment" asp-action="Edit" asp-route-id=@e.EnrollmentId class="btn btn-info"> Edit </a>
                    <a asp-controller="Enrollment" asp-action="Delete" asp-route-id="@e.EnrollmentId" class="btn btn-info"> Delete </a>
                </td>
            </tr>
        }
    </tbody>
</table>
<form asp-action="Add" method="get">
    <button type="submit" class="btn btn-info"> Add Enrollments </button>
</form>