SMS/Models/Domain/Instructor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SMS.Models
{
    public class Instructor
    {
        public int InstructorId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }

    }
}

SMS/Controllers/InstructorController.cs
using Microsoft.AspNetCore.Mvc;
using SMS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SMS.Controllers
{
    public class InstructorController : Controller
    {
        private StudentContext context { get; set; }

        public InstructorController(StudentContext ctx)
        {
            context = ctx;
        }
        public IActionResult Index()
        {
            var instructors = context.Instructors.OrderBy(i=>i.InstructorId).ToList();
            return View(instructors);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Instructor i)
        {
            if (ModelState.IsValid)
            {
                context.Instructors.Add(i);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(i);
            }
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var i = context.Instructors.Find(id);
            return View(i);
        }
        [HttpPost]
        public IActionResult Edit(Instructor i)
        {
            if (ModelState.IsValid)
            {
                context.Instructors.Update(i);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(i);
            }
        }
        [HttpGet]
        public IActionResult Delete (int id)
        {
            var i = context.Instructors.Find(id);
            return View(i);
        }
        [HttpPost]
        public IActionResult Delete (Instructor i)
        {
            context.Instructors.Remove(i);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

SMS/Views/Instructor/Add.cshtml
@model Instructor

<h3>Add New Instructor</h3>
<form asp-action="Add" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name">Name:</label>
        <input type="text" asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Email">Email:</label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Add" class="btn btn-info" />
        <a asp-action="Index" class="btn btn-warning">Cancel</a>
    </div>
</form>

SMS/Views/Instructor/Delete.cshtml
@model Instructor
@{
    ViewData["Title"] = "Delete";
}

<h3>Delete</h3>
<h4>Are you sure you want to remove this instructor?</h4>
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
    <form asp-action="Delete" method="post">
        <input type="hidden" asp-for="InstructorId" />
        <button type="submit" class="btn btn-danger"> Delete </button>
        <a asp-action="Index" class="btn btn-warning">Cancel</a>
    </form>
</div>

SMS/Views/Instructor/Edit.cshtml
@model Instructor

<h3>Edit Instructors</h3>
<form asp-action="Edit" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="InstructorId" />
    <div class="form-group">
        <label asp-for="Name">Name:</label>
        <input type="text" asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email">Email:</label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Edit" class="btn btn-info" />
        <a asp-action="Index" class="btn btn-warning">Cancel</a>
    </div>
</form>

SMS/Views/Instructor/Index.cshtml
@model List<Instructor>
@{
    ViewBag.Title = "Instructors";
}

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var i in Model)
        {
            <tr>
                <td>@i.InstructorId</td>
                <td>@i.Name</td>
                <td>@i.Email</td>

                <td>
                    <a asp-controller="Instructor" asp-action="Edit" asp-route-id=@i.InstructorId class="btn btn-info"> Edit </a>
                    <a asp-controller="Instructor" asp-action="Delete" asp-route-id="@i.InstructorId" class="btn btn-info"> Delete </a>
                </td>
            </tr>
        }
    </tbody>
</table>
<form asp-action="Add" method="get">
    <button type="submit" class="btn btn-info"> Add Instructors </button>
</form>