SMS/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using SMS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SMS.Controllers
{
    public class CourseController : Controller
    {
        private StudentContext context { get; set; }

        public CourseController(StudentContext ctx)
        {
            context = ctx;
        }
        public IActionResult Index()
        {
            ViewBag.Instructors = context.Instructors.OrderBy(i => i.Name).ToList();
            ViewBag.Majors = context.Majors.OrderBy(m => m.Title).ToList();
            var courses = context.Courses.OrderBy(c => c.CourseId).ToList();
            return View(courses);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Course c)
        {
            if (ModelState.IsValid)
            {
                context.Courses.Add(c);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(c);
            }
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var c = context.Courses.Find(id);
            return View(c);
        }
        [HttpPost]
        public IActionResult Edit(Course c)
        {
            if (ModelState.IsValid)
            {
                context.Courses.Update(c);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(c);
            }
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var c = context.Courses.Find(id);
            return View(c);
        }
        [HttpPost]
        public IActionResult Delete(Course c)
        {
            context.Courses.Remove(c);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

SMS/Controllers/MajorController.cs
using Microsoft.AspNetCore.Mvc;
using SMS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SMS.Controllers
{
    public class MajorController : Controller
    {
        private StudentContext context { get; set; }

        public MajorController(StudentContext ctx)
        {
            context = ctx;
        }
        public IActionResult Index()
        {
            var majors = context.Majors.OrderBy(m => m.MajorId).ToList();
            return View(majors);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Major m)
        {
            if (ModelState.IsValid)
            {
                context.Majors.Add(m);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(m);
            }
        }
        [HttpGet]
        public IActionResult Delete (int id)
        {
            var m = context.Majors.Find(id);
            return View(m);
        }
        [HttpPost]
        public IActionResult Delete(Major m)
        {           
            context.Majors.Remove(m);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

SMS/Controllers/MajoringController.cs
using Microsoft.AspNetCore.Mvc;
using SMS.Models;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;

namespace SMS.Controllers
{
    public class MajoringController : Controller
    {
        private StudentContext context { get; set; }

        public MajoringController(StudentContext ctx)
        {
            context = ctx;
        }
        public IActionResult Index()
        {
            dynamic mymodel = new ExpandoObject();
            ViewBag.Students = context.Students.OrderBy(s => s.Name).ToList();
            ViewBag.Majors = context.Majors.OrderBy(m => m.Title).ToList();
            
            mymodel.Majorings = context.Majorings.OrderBy(ma => ma.StudentId).ToList();
            mymodel.Majors = context.Majors.OrderBy(m => m.MajorId).ToList();
            mymodel.Students = context.Students.OrderBy(s => s.StudentId).ToList();
            return View(mymodel);
        }
        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Students = context.Students.ToList();
            ViewBag.Majors = context.Majors.ToList();
            return View();
        }
        [HttpPost]
        public IActionResult Add(Majoring m)
        {
            if (ModelState.IsValid)
            {
                context.Majorings.Add(m);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Students = context.Students.ToList();
                ViewBag.Majors = context.Majors.ToList();
                return View(m);
            }
        }
        
    }
}

SMS/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using SMS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SMS.Controllers
{
    public class StudentController : Controller
    {
        private StudentContext context { get; set; }

        public StudentController(StudentContext ctx)
        {
            context = ctx;
        }
        public IActionResult Index()
        {
            var students = context.Students.OrderBy(s => s.StudentId).ToList();
            return View(students);
        }
        public IActionResult Details(int id)
        {
            Student s = context.Students.Find(id);
            return View(s);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Student s)
        {
            if (ModelState.IsValid)
            {
                context.Students.Add(s);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(s);
            }
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var s = context.Students.Find(id);
            return View(s);
        }
        [HttpPost]
        public IActionResult Edit(Student s)
        {
            if (ModelState.IsValid)
            {
                context.Students.Update(s);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(s);
            }
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var s = context.Students.Find(id);
            return View(s);
        }
        [HttpPost]
        public IActionResult Delete(Student s)
        {
            context.Students.Remove(s);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

SMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SMS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SMS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instructor" asp-action="Index">Instructor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Major" asp-action="Index">Major</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Course</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Majoring" asp-action="Index">Majoring</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Enrollment" asp-action="Index">Enroll</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SMS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>